# Generated by Django 4.2.7 on 2023-11-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_category_trainingarticle_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='good_topics',
            field=models.ManyToManyField(related_name='user_profiles_with_good_topics', to='article.category'),
        ),
    ]
