# Generated by Django 4.2.7 on 2023-11-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_remove_userprofile_bad_topics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='read_articles',
            field=models.ManyToManyField(blank=True, related_name='read_by_users', to='article.article'),
        ),
    ]
