# Generated by Django 4.2.7 on 2023-11-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_userprofile_read_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bag_of_words_matrix',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='feature_names',
            field=models.TextField(null=True),
        ),
    ]
