# Generated by Django 4.2.7 on 2023-11-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_userprofile_bag_of_words_matrix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bag_of_words_matrix',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='feature_names',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trainingarticle',
            name='bag_of_words_matrix',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='trainingarticle',
            name='feature_names',
            field=models.TextField(null=True),
        ),
    ]
