# Generated by Django 4.2.7 on 2023-11-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_article_bag_of_words_matrix_article_feature_names_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bag_of_words_matrix',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='feature_names',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_article',
            field=models.ManyToManyField(null=True, related_name='last_article', to='article.article'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='read_articles',
            field=models.ManyToManyField(null=True, related_name='read_by_users', to='article.article'),
        ),
    ]
