# Generated by Django 4.2.7 on 2023-11-10 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_remove_userprofile_bag_of_words_matrix_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_article',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_article', to='article.article'),
        ),
    ]
