# Generated by Django 4.2.7 on 2023-11-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_remove_userprofile_last_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='read_articles',
            field=models.ManyToManyField(related_name='read_by_users', to='article.article'),
        ),
    ]
