# Generated by Django 4.2.7 on 2023-11-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_alter_userprofile_read_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_article',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='read_articles',
            field=models.ManyToManyField(blank=True, default=[], related_name='read_by_users', to='article.article'),
        ),
    ]
