# Generated by Django 4.2.7 on 2023-11-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dislike_articles',
            field=models.ManyToManyField(blank=True, default=[], related_name='dislike_articles', to='article.article'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='like_articles',
            field=models.ManyToManyField(blank=True, default=[], related_name='like_articles', to='article.article'),
        ),
    ]
