# Generated by Django 4.2.7 on 2023-11-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_article_dislikes_article_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='dislikes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
