# Generated by Django 4.2.7 on 2023-11-24 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_alter_article_dislikes_alter_article_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='trainingarticle',
            name='bag_of_words_matrix',
        ),
        migrations.RemoveField(
            model_name='trainingarticle',
            name='feature_names',
        ),
        migrations.AddField(
            model_name='trainingarticle',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.country'),
        ),
    ]
