# Generated by Django 4.2.7 on 2024-01-08 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_alter_trainingarticle_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingarticle',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.country'),
        ),
    ]
